### ISSUE TITLE
Missing .d.ts for import in vite.config.ts

### ISSUE THREAD

**Issue by nicolas-albert** [carlosV2/adapter-node-ws#2]
Hi, thanks for your plugin.
I'm on a svelte project configured to use TS and I have a vite.config.ts like that:
```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()]
});
```
In cannot do that:
```import WebSockets from "@carlosv2/adapter-node-ws/plugin"``` nor ```import * as WebSockets from '@carlosv2/adapter-node-ws/plugin'```

Do you have any clue?

Thx!

**Comment by carlosV2** [comment]
Oh! Apologies, that was actually my fault. I forgot to export `plugin.d.ts`. Pulling the version `0.1.4` should fix it for you.

Thanks for letting me know!

**Comment by nicolas-albert** [comment]
Ok, now I have an issue to import `WebSocketServer` in `hooks.server.ts` but this isn't caused by your plugin.
I still cannot test and I've switched to a solution without WS for now.

**Comment by carlosV2** [comment]
I see. Ok, I'll close this issue for now then. Let me know if you have other issues I can help you with :-)
